[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"


[project]
name="dlk"
authors = [
    {name = "cstsunfu", email = "cstsunfu@gmail.com"},
]
readme = "README.md"
dynamic = ["version", "license", "description"]
requires-python = ">=3.11"
keywords = ["dlk", "pytorch", "lightning"]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: Apache Software License"
]

dependencies = [
    "intc>=0.1.1,<0.3",
    "hjson>=3.0.2",
    "pandas>=2.0",
    "fsspec>=2023.5,<=2025.5",
    "tabulate>=0.9.0,<=1.0",
    "pyarrow>=10.0.1",
    "ray[train,tune,serve]>=2.40.0,<3.0",
    "transformers>=4.47.0,<6.0",
]

[project.optional-dependencies]
train = [
    "lightning>=2.6.0,<=3.0",
    "torch>=2.5,<=2.10",
    "torchmetrics>=1.2.1",
    "tensorboard>=2.7.0,<3.0",
    "datasets>=4.0.0",
    "optuna>=4.4.0,<5.0",
    "optuna-dashboard>=0.19.0",
    "sqlalchemy>=2.0.0,<3.0",
    "alembic>=1.10.0,<2.0",
]

export = [
    "dlk[train]",
    "onnx>=1.18.0,<2.0",
    "onnxruntime>=1.15.0,<2.0",
]

process = [
    "datasets>=4.0.0",
]

extra = [
    "streamlit>=1.32",
    "svgwrite>=1.4",
    "pyecharts>=2.0",
]

all = [
    "dlk[train]",
    "dlk[export]",
    "dlk[process]",
    "dlk[extra]",
]
